### PR TITLE
Compatibility fix for PHP 8.0.0

### PR DESCRIPTION
**Pull request by fpoirotte**
See https://bugs.php.net/bug.php?id=79869

### CODE REVIEW

**Comment by fpoirotte** [comment]
The issue also presents itself when trying to install PEAR using https://pear.php.net/install-pear-nozlib.phar.

The commit fixes the error, but I haven't been able to test it thouroughly because when I tried to update the stub for the PHAR, PHP later complained about the manifest's length being incorrect:
```
ERROR: manifest length read was "3590244" should be "540748072"
```

I'm not really sure if this is related to my change (the previous code probably never worked as intended due to the type mismatch, but fixing it may have triggered another bug) or if it stems from an issue with my test setup.

**Comment by nikic** [comment]
@ashnazg Could you please take a look at this one?

**Comment by rickyrocker** [comment]
@ashnazg yes please can you help!

**Comment by rickyrocker** [comment]
@ashnazg please please can you help with this as we are unable to upgrade to PHP 8 because of this problem. It really is very serious for us. Thank you!!

**Comment by ashnazg** [comment]
I'll try to have a look by the weekend... watching tornadoes at the moment 😱

**Comment by rickyrocker** [comment]
> 
> 
> I'll try to have a look by the weekend... watching tornadoes at the moment 😱

Oh my word! Thanks so much @ashnazg

**Comment by rickyrocker** [comment]
Hi @ashnazg - hope the weather has stabilized your side! Just checking in to find out whether any progress on the fix? (looks like a tiny commit done by @fpoirotte so am hoping not to tricky to confirm) - thanks!

**Review by ashnazg — APPROVED** [review]

**Comment by ashnazg** [comment]
v0.14.0 released

**Comment by rickyrocker** [comment]
Thank you so much @ashnazg ! 

Apologies in advance for this stupid question as this is something new for me :

I'm wanting to compile php 8 again with the --with-pear=shared option.

Do I need to wait for the next 8.0.x release of PHP for this fix to go in or is there a way i can make pear 0.14.0 available for the current installation of PHP 8?

Thanks!

**Comment by rickyrocker** [comment]
(I mean PHP_Archive 0.14.0  :) )

**Comment by ashnazg** [comment]
`pear upgrade php_archive` should upgrade it in place if it's already installed... you might need `sudo` depending on how it's currently installed.

If it's not already installed, then `pear install php_archive` should suffice.

**Comment by rickyrocker** [comment]
Thanks again @ashnazg - will give it a go!

**Pull request merged**
